/*
 * This file was generated by LibCSS gen_parser 
 * 
 * Generated from:
 *
 * background_image:CSS_PROP_BACKGROUND_IMAGE IDENT:( INHERIT: NONE:0,BACKGROUND_IMAGE_NONE IDENT:) URI:BACKGROUND_IMAGE_URI
 * 
 * Licensed under the MIT License,
 *		  http://www.opensource.org/licenses/mit-license.php
 * Copyright 2010 The NetSurf Browser Project.
 */

#include <assert.h>
#include <string.h>

#include "bytecode/bytecode.h"
#include "bytecode/opcodes.h"
#include "parse/properties/properties.h"
#include "parse/properties/utils.h"

/**
 * Parse background_image
 *
 * \param c	  Parsing context
 * \param vector  Vector of tokens to process
 * \param ctx	  Pointer to vector iteration context
 * \param result  resulting style
 * \return CSS_OK on success,
 *	   CSS_NOMEM on memory exhaustion,
 *	   CSS_INVALID if the input is not valid
 *
 * Post condition: \a *ctx is updated with the next token to process
 *		   If the input is invalid, then \a *ctx remains unchanged.
 */
css_error css__parse_background_image(css_language *c,
		const parserutils_vector *vector, int *ctx,
		css_style *result)
{
	int orig_ctx = *ctx;
	css_error error;
	const css_token *token;
  uint16_t value = 0;

	token = parserutils_vector_iterate(vector, ctx);
	if (token == NULL) {
		*ctx = orig_ctx;
		return CSS_INVALID;
	}

  if (token->type == CSS_TOKEN_IDENT) {
    if (is_css_keyword(c, token, INHERIT))
      error = css_stylesheet_style_inherit(result, CSS_PROP_BACKGROUND_IMAGE);
    else if (is_css_keyword(c, token, NONE))
      error = css__stylesheet_style_appendOPV(result, CSS_PROP_BACKGROUND_IMAGE, 0,BACKGROUND_IMAGE_NONE);
    else
      error = CSS_INVALID;
    if (error != CSS_OK)
      *ctx = orig_ctx;
    return error;
  }

  if (token->type == CSS_TOKEN_URI) {
    lwc_string *uri = NULL;
    uint32_t uri_snumber;

    error = c->sheet->resolve(c->sheet->resolve_pw,
                              c->sheet->url,
                              token->idata, &uri);
    if (error != CSS_OK)
      goto invalid;

    error = css__stylesheet_string_add(c->sheet, uri, &uri_snumber);
    if (error != CSS_OK)
      goto invalid;

    error = css__stylesheet_style_appendOPV(result, CSS_PROP_BACKGROUND_IMAGE, 0, BACKGROUND_IMAGE_URI);
    if (error != CSS_OK)
      goto invalid;

    error = css__stylesheet_style_append(result, uri_snumber);
    if (error != CSS_OK)
      *ctx = orig_ctx;
    return error;
  }

  if (token->type != CSS_TOKEN_FUNCTION) {
    error = CSS_INVALID;
    goto invalid;
  }

  if (is_css_keyword(c, token, LINEAR_GRADIENT))
    value = BACKGROUND_IMAGE_LINEAR_GRADIENT;
  else if (is_css_keyword(c, token, REPEATING_LINEAR_GRADIENT))
    value = BACKGROUND_IMAGE_REPEATING_LINEAR_GRADIENT;
  else if (is_css_keyword(c, token, RADIAL_GRADIENT))
    value = BACKGROUND_IMAGE_RADIAL_GRADIENT;
  else if (is_css_keyword(c, token, REPEATING_RADIAL_GRADIENT))
    value = BACKGROUND_IMAGE_REPEATING_RADIAL_GRADIENT;
  else
  {
      error = CSS_INVALID;
      goto invalid;
  }

  error = css__stylesheet_style_appendOPV(result, CSS_PROP_BACKGROUND_IMAGE, 0, value);
  if (error != CSS_OK)
    goto invalid;

  if (value == BACKGROUND_IMAGE_LINEAR_GRADIENT || value == BACKGROUND_IMAGE_REPEATING_LINEAR_GRADIENT) {
    error = css__parse_linear_gradient(c, vector, ctx, result);
    if (error != CSS_OK)
      goto invalid;
  } else {
    /* TODO:radial-gradient */
    error = CSS_OK;
  }

	return CSS_OK;

invalid:
  *ctx = orig_ctx;
	return error;
}

